// ============================================================================
// ENABLER PROFILES DATA
// 100 users classified by their behavior in ASL and Jenna's chats
// ============================================================================

export type Classification =
  | "INFILTRATOR"
  | "FALSE_NEUTRAL"
  | "ENABLER"
  | "CENSOR"
  | "FLYING_MONKEY";

export type TacticCategory =
  | "DARVO_ATTACK"
  | "PATHOLOGIZE"
  | "DARVO_REVERSE"
  | "MINIMIZE"
  | "FALSE_EQUIVALENCE"
  | "WEAPONIZED_MOVE_ON"
  | "CREDIBILITY_ATTACK"
  | "DISCOURAGE_LEGAL";

export interface WorstMessage {
  message: string;
  category: TacticCategory;
  source: "asl_chat" | "jenna_chat";
}

export interface EnablerProfile {
  username: string;
  enabler_score: number;
  classification: Classification;
  is_moderator: boolean;
  asl_message_count: number;
  jenna_message_count: number;
  gaslighting_count: number;
  pressure_count: number;
  worst_messages: WorstMessage[];
  categories_triggered: TacticCategory[];
  category_counts: Partial<Record<TacticCategory, number>>;
  is_infiltrator?: boolean;
}

export const CLASSIFICATION_INFO: Record<Classification, { label: string; description: string; color: string }> = {
  INFILTRATOR: {
    label: "Infiltrator",
    description: "Appeared in both chats, used pressure tactics in Jenna's chat",
    color: "toxic",
  },
  FALSE_NEUTRAL: {
    label: "False Neutral",
    description: "Pushed 'both sides' false equivalence",
    color: "coral",
  },
  ENABLER: {
    label: "Enabler",
    description: "Supported abuser narrative in ASL's chat",
    color: "shame",
  },
  CENSOR: {
    label: "Censor",
    description: "Active moderator suppressing dissent",
    color: "verdict",
  },
  FLYING_MONKEY: {
    label: "Flying Monkey",
    description: "Direct attack dog for the abuser",
    color: "toxic",
  },
};

export const TACTIC_INFO: Record<TacticCategory, { label: string; description: string }> = {
  DARVO_ATTACK: {
    label: "DARVO Attack",
    description: "Weaponized 'therapy' and 'mental health' language against the victim",
  },
  PATHOLOGIZE: {
    label: "Armchair Diagnosis",
    description: "Diagnosing the victim with BPD or other disorders",
  },
  DARVO_REVERSE: {
    label: "Victim Reversal",
    description: "Making the victim seem like the aggressor",
  },
  MINIMIZE: {
    label: "Minimize",
    description: "Downplaying the severity of abuse",
  },
  FALSE_EQUIVALENCE: {
    label: '"Both Sides"',
    description: "Treating abuser and victim as equally at fault",
  },
  WEAPONIZED_MOVE_ON: {
    label: '"Move On"',
    description: "Pressuring victim to stay silent and drop it",
  },
  CREDIBILITY_ATTACK: {
    label: '"Dirty Laundry"',
    description: "Shaming victim for speaking publicly",
  },
  DISCOURAGE_LEGAL: {
    label: "Discourage Legal",
    description: "Explicit attempts to prevent legal action",
  },
};

export const ENABLER_STATS = {
  total: 100,
  byClassification: {
    INFILTRATOR: 50,
    FALSE_NEUTRAL: 27,
    ENABLER: 20,
    CENSOR: 2,
    FLYING_MONKEY: 1,
  },
};

// All 100 enabler profiles
export const ENABLER_PROFILES: EnablerProfile[] = [
  {
    username: "doaisafraud",
    enabler_score: 40,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 20,
    worst_messages: [
      { message: "Jenna, both of you need to stop! Your personal life is NO ONE'S business. You are a strong independent woman and will be fine! You don't need go play the same game!", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "Jenna, relationships can be messy. It happens to everyone! You 2 aren't a good fit. You both need to realize this and let it go! Stop giving these people fodder!", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "@JennaMiscavige, Please be the bigger person. You DON'T need to do this. People are enjoying the both of you 2 going at each other and will try and take advantage of the situation", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE", "WEAPONIZED_MOVE_ON"],
    category_counts: { FALSE_EQUIVALENCE: 9, WEAPONIZED_MOVE_ON: 11 },
    is_infiltrator: false,
  },
  {
    username: "genxray",
    enabler_score: 38,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 48,
    gaslighting_count: 1,
    pressure_count: 15,
    worst_messages: [
      { message: "I am listening to the start and a few minutes in it is clear she has borderline Personality disorder. two choices for you learn about BPD and know its from trauma or stay away from her full stop NOW", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I have been married 17 years to someone with Borderline Personality Disorder. Both of you need to learn what it is and be real that your fears and trauma is because of the cult. His mod blocked me btw", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "You have reason to be angry but he has reason to be confused about your fear of abandonment. you both see this is BECAUSE of Scientology. THEY want this and you both should understand that now", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "both of you have a lot of trauma and the people on here judging either of you are most likely in the cult- laughing. THIS is the sickness that makes you both hurt", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "you both need to learn about borderline personality disorder and how to learn to regulate your emotions - what you were not taught in the cult. your feelings are valid but you so are his.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "FALSE_EQUIVALENCE", "WEAPONIZED_MOVE_ON"],
    category_counts: { DARVO_ATTACK: 1, FALSE_EQUIVALENCE: 14, WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "meowdy-there",
    enabler_score: 30,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 64,
    jenna_message_count: 41,
    gaslighting_count: 7,
    pressure_count: 2,
    worst_messages: [
      { message: "Please don't diagnose in the comments. Encourage to seek help and support", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "Let's keep it clear, for the people spewing off, having abandonment issues doesn't make you a dirty, unworthy person! It's how you choose to heal from that.", category: "PATHOLOGIZE", source: "asl_chat" },
      { message: "Therapy doesn't FIX but it gives you the TOOLS to heal. You still have to do the work yourself and a lot of self acknowledgement and introspection.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "Please no psycho analyzing", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I will say some therapists were not helpful to me but it's worth a shot. Group therapy helped me the most personally!", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "PATHOLOGIZE", "FALSE_EQUIVALENCE", "CREDIBILITY_ATTACK"],
    category_counts: { DARVO_ATTACK: 6, PATHOLOGIZE: 1, FALSE_EQUIVALENCE: 1, CREDIBILITY_ATTACK: 1 },
    is_infiltrator: true,
  },
  {
    username: "christicovington",
    enabler_score: 22,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 7,
    jenna_message_count: 5,
    gaslighting_count: 3,
    pressure_count: 4,
    worst_messages: [
      { message: "I think both of you need to be alone and focus on yourselves and your own mental health. Praying for you, Aaron, and her as well. I hope you find some peace in your life after this breakup.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "we are all responsible for our own behavior. blaming Aaron for her bad behavior is insane. she needs to seek help and find peace. I'm praying for you both.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I hope that you both seek mental health support. You've been through a traumatic relationship and she clearly has rage issues as well as major insecurities.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "Jenna I'm praying for you both. I hope that you're able to find some peace and start holding yourself accountable. You're in control of your behavior. Just move on and let it go. This isn't healthy.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "WEAPONIZED_MOVE_ON", "FALSE_EQUIVALENCE"],
    category_counts: { DARVO_ATTACK: 3, WEAPONIZED_MOVE_ON: 3, FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "spongebobsqueeze",
    enabler_score: 22,
    classification: "FLYING_MONKEY",
    is_moderator: false,
    asl_message_count: 5,
    jenna_message_count: 0,
    gaslighting_count: 9,
    pressure_count: 0,
    worst_messages: [
      { message: "I'm so sorry. I can see how much you and Jenna liked each other and i know you hoped it would work.i was hoping that the therapy she was seeking for her abandonment issues was helping her more.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I'm so sorry. I can see how much you and Jenna liked each other and i know you hoped it would work.i was hoping that the therapy she was seeking for her abandonment issues was helping her more.", category: "PATHOLOGIZE", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "PATHOLOGIZE"],
    category_counts: { DARVO_ATTACK: 4, PATHOLOGIZE: 5 },
  },
  {
    username: "markus5862",
    enabler_score: 20,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 17,
    jenna_message_count: 8,
    gaslighting_count: 2,
    pressure_count: 5,
    worst_messages: [
      { message: "A shame if Jenna leaves because she was a really great source and voice in exposing things. Hopefully when the emotions and dust clears up, she chooses to stay", category: "PATHOLOGIZE", source: "asl_chat" },
      { message: "This isn't a knock but I wish the two would actually give therapy a chance. I know it's been boiled into their minds that it's useless but it really really isn't and would be so helpful", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "It's so unnecessary the two of them have to do this because they both were threatening one another. They couldn't just move on from one another and live their lives", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "It's just unfortunate that it's come to this for both and they couldn't just move on from one another", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "I think they're both at fault to be perfectly honest with you and they both threatened each other. There's no one person at fault and it's a shame it's come to this", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["PATHOLOGIZE", "DARVO_ATTACK", "WEAPONIZED_MOVE_ON", "FALSE_EQUIVALENCE"],
    category_counts: { PATHOLOGIZE: 1, DARVO_ATTACK: 1, WEAPONIZED_MOVE_ON: 3, FALSE_EQUIVALENCE: 2 },
    is_infiltrator: true,
  },
  {
    username: "luvpurecom",
    enabler_score: 16,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 18,
    jenna_message_count: 1,
    gaslighting_count: 3,
    pressure_count: 1,
    worst_messages: [
      { message: "$75 for therapy better than repeating this pattern?", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "@meowdy-there The trick seems to be to find \"complimentary damage\". We're all crazy, the key is finding people who are your kind of crazy.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "Who thinks we could raise $75 per therapy session for Aaron?", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "You both couldn't just break up, and not saying anything? Who posted first about this?", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "FALSE_EQUIVALENCE"],
    category_counts: { DARVO_ATTACK: 3, FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "kathy1944",
    enabler_score: 16,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 11,
    jenna_message_count: 3,
    gaslighting_count: 3,
    pressure_count: 1,
    worst_messages: [
      { message: "They have been through a lot. They both need help. Sending you Aaron and Jenna hugs, and wishing you both of you happiness.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "They both need help. The cult Fd them both UP big time. Sending blessings to Aaron, and Jenna.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I really feel bad for them both. JENNA please get help!!!!!", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "Because of the CULT they are both are Fed up. They both need help so much", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "FALSE_EQUIVALENCE"],
    category_counts: { DARVO_ATTACK: 3, FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "wendyh10",
    enabler_score: 15,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 18,
    jenna_message_count: 35,
    gaslighting_count: 2,
    pressure_count: 2,
    worst_messages: [
      { message: "I'm so grateful for therapy and meds.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I'm team their children. Get help.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I wish you both loved your children enough to stop publicly humiliating them.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "The language you both use is foul", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "FALSE_EQUIVALENCE"],
    category_counts: { DARVO_ATTACK: 2, FALSE_EQUIVALENCE: 2 },
    is_infiltrator: true,
  },
  {
    username: "asefrydenlund",
    enabler_score: 14,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 9,
    jenna_message_count: 2,
    gaslighting_count: 2,
    pressure_count: 2,
    worst_messages: [
      { message: "Oh may this sounds horrible, but as you say, she needs help to control her anger and fear of being left. Normal relationship is difficult, but even harder for you", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "In a relationship its never only 1 that are correct. It takes two to dance a tango.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "Jenna, please you have receipt, and he has receipt. Its no winner here. Please move on and heal and get into a healthy relationship.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "PATHOLOGIZE", "FALSE_EQUIVALENCE", "WEAPONIZED_MOVE_ON"],
    category_counts: { DARVO_ATTACK: 1, PATHOLOGIZE: 1, FALSE_EQUIVALENCE: 1, WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "meghanisacat",
    enabler_score: 13,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 6,
    jenna_message_count: 1,
    gaslighting_count: 2,
    pressure_count: 1,
    worst_messages: [
      { message: "This might be a good opportunity for both of you to get some therapy to start healing, individually. You've both had a lot of trauma. I got EMDR for my trauma and it REALLY helped.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "Oh, Aaron. You sound so hurt. I know you spoke the other day of not wanting to pay for therapy, but it could really help you. You've been through so much. Same goes for Jenna. You both deserve healing", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I really hope you both get some therapy. Scientology has hurt you both and you both deserve to feel better and form healthy relationships.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "FALSE_EQUIVALENCE"],
    category_counts: { DARVO_ATTACK: 2, FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "stephaniea925",
    enabler_score: 13,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 35,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "Did you seriously phone the cops? that's low. Just walk away.", category: "DISCOURAGE_LEGAL", source: "jenna_chat" },
      { message: "@QueenOfKarma there's plenty of books, but they definitely won't help.", category: "DISCOURAGE_LEGAL", source: "jenna_chat" },
    ],
    categories_triggered: ["DISCOURAGE_LEGAL"],
    category_counts: { DISCOURAGE_LEGAL: 2 },
    is_infiltrator: true,
  },
  {
    username: "lindabedwell807",
    enabler_score: 13,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 14,
    jenna_message_count: 41,
    gaslighting_count: 0,
    pressure_count: 4,
    worst_messages: [
      { message: "I'm embarrassed for both of you", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "You BOTH stayed.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "Both of you are SO wrong to this publicly.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "Jenna this doesn't make either of you look good. Pathetic on both of you.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 4 },
    is_infiltrator: true,
  },
  {
    username: "jess-3675",
    enabler_score: 13,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 6,
    jenna_message_count: 3,
    gaslighting_count: 0,
    pressure_count: 4,
    worst_messages: [
      { message: "You both have issues and need to stay away from each other. Grow up.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "Doing this makes it worse. Both of you need to grow up.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON", "FALSE_EQUIVALENCE"],
    category_counts: { WEAPONIZED_MOVE_ON: 2, FALSE_EQUIVALENCE: 2 },
    is_infiltrator: true,
  },
  {
    username: "doesitmatter2unot2me46",
    enabler_score: 12,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 29,
    jenna_message_count: 21,
    gaslighting_count: 1,
    pressure_count: 2,
    worst_messages: [
      { message: "Thanks you Mods for trying to keep it clean in here. This is part of his own Therapy.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "Just because you have broken up, i wish you both can reconcile and still be friends and continue the fight against COS.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "@JennaMiscavige Im still here. I hope you both can get through this and heal.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "FALSE_EQUIVALENCE"],
    category_counts: { DARVO_ATTACK: 1, FALSE_EQUIVALENCE: 2 },
    is_infiltrator: true,
  },
  {
    username: "ragnarkisten",
    enabler_score: 12,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 6,
    worst_messages: [
      { message: "I am being completely honest about things I know little about, but I think you both need help! I think your upbringing has damaged you both!", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "I think you both need to control your theta!", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "I think Xenu has possessed you both!", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "all this drama cramps both of your styles. Don't be like your uncle Jenna!", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "Xenu is so disappointed in you both!", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 6 },
    is_infiltrator: false,
  },
  {
    username: "watchinglivestreams4352",
    enabler_score: 12,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 6,
    worst_messages: [
      { message: "What is against the law here? Sounds like a lovers quarrel. You guys need to end it and both move on.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "Just be done with this. END it. Don't try to destroy each other. Act like adults and just move on. Some will support you, some him. That's not healthy. Just end it and move on!", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "Just move on!!", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "People will NOT support you trying to get him arrested again. Just sayin. Just MOVE on.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON"],
    category_counts: { WEAPONIZED_MOVE_ON: 6 },
    is_infiltrator: false,
  },
  {
    username: "arkansasflamingo",
    enabler_score: 11,
    classification: "CENSOR",
    is_moderator: true,
    asl_message_count: 140,
    jenna_message_count: 0,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "please be respectful, don't diagnose mental issues, and remember that we love them both. Negative comments will be deleted", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "Marilyn, if I wasn't on medication, I'd be in trouble sister, it's okay to get help.", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 2 },
  },
  {
    username: "bumblebeetuna477",
    enabler_score: 11,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 4,
    gaslighting_count: 0,
    pressure_count: 3,
    worst_messages: [
      { message: "This all needs to stop after this. I get that you both needed to get it off yoir chest, but stop putting this on the internet. It isn't a good look for either of you.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "Just stay away from each other. You have both done wrong things in this relationship. Just leave it be and move on.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "Don't put anything together....just let it go and move on.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE", "WEAPONIZED_MOVE_ON"],
    category_counts: { FALSE_EQUIVALENCE: 1, WEAPONIZED_MOVE_ON: 2 },
    is_infiltrator: true,
  },
  {
    username: "hopeynay",
    enabler_score: 10,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 9,
    jenna_message_count: 11,
    gaslighting_count: 1,
    pressure_count: 1,
    worst_messages: [
      { message: "You need therapy. She needs therapy. Y'all need to walk your separate ways.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I was just put in time out in his live. Basically, I hope both of you decide to just be done.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "FALSE_EQUIVALENCE"],
    category_counts: { DARVO_ATTACK: 1, FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "zerozerodashero",
    enabler_score: 10,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 6,
    jenna_message_count: 5,
    gaslighting_count: 1,
    pressure_count: 1,
    worst_messages: [
      { message: "Sounds exactly like the use case for therapy", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "please, please, please close this chapter and reopen it in therapy. You both are so good intentioned, but really need to replace the firm ways of dealing with things that are influenced by sciento", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "FALSE_EQUIVALENCE"],
    category_counts: { DARVO_ATTACK: 1, FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "roguemomma25",
    enabler_score: 10,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 1,
    gaslighting_count: 1,
    pressure_count: 1,
    worst_messages: [
      { message: "Both people in this relationship are damaged and both need therapy separate. They shouldn't be in a relationship", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "This is not normal healthy adult behavior for you Both. Get off the internet", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "FALSE_EQUIVALENCE"],
    category_counts: { DARVO_ATTACK: 1, FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "antonslavik",
    enabler_score: 10,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 21,
    gaslighting_count: 1,
    pressure_count: 1,
    worst_messages: [
      { message: "No! Not therapy as a couple. That's dangerous", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "Jenna, you've both suffered enough. Please move on after this.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "WEAPONIZED_MOVE_ON"],
    category_counts: { DARVO_ATTACK: 1, WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "rachelles3275",
    enabler_score: 10,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 7,
    jenna_message_count: 1,
    gaslighting_count: 1,
    pressure_count: 1,
    worst_messages: [
      { message: "She talked about fear of abandonment on the Tim Fletcher podcast. I wish a path to better mental health for both is sought out.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "It's just time to move on and find a path to a healthier you", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "WEAPONIZED_MOVE_ON"],
    category_counts: { DARVO_ATTACK: 1, WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "kateashley950",
    enabler_score: 10,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 2,
    gaslighting_count: 1,
    pressure_count: 1,
    worst_messages: [
      { message: "such BS reactions are a choice. she needs therapy major trauma therapy. not being a psycho", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "here is an idea ! Stop getting back together, it will be the best for you both", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "FALSE_EQUIVALENCE"],
    category_counts: { DARVO_ATTACK: 1, FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "queenofkarma",
    enabler_score: 10,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 5,
    worst_messages: [
      { message: "Jenna won't mod any of you. She doesn't trust randoms online. You tend not to when you grow up in a cult...", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "Jenna isn't out for blood, he might be. So Jenna will respond, empower herself and move on. He wont listen.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "Ya Jenna, it might be better if you don't ask ppl to chose sides, mainly for YOUR PEACE. If it bothers you ppl chose to continue speaking to him, cut them off for a bit if you need to.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "Ya Jenna move on from him, you deserve better than this", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "YES HEAL FIRST JENNA AND THEN ADDRESS IT. FOR YOUR OWN PEACE.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON"],
    category_counts: { WEAPONIZED_MOVE_ON: 5 },
    is_infiltrator: false,
  },
  {
    username: "karenm8239",
    enabler_score: 10,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 1,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "@QueenOfKarma I was silenced on his stream because I said they should both stop airing dirty laundry although I did say no offence but it needs to stop", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON", "CREDIBILITY_ATTACK"],
    category_counts: { WEAPONIZED_MOVE_ON: 1, CREDIBILITY_ATTACK: 1 },
    is_infiltrator: true,
  },
  {
    username: "jamaicazipfel9088",
    enabler_score: 9,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 44,
    jenna_message_count: 0,
    gaslighting_count: 3,
    pressure_count: 0,
    worst_messages: [
      { message: "She needs therapy not a relationship. she needs onw tih herself. That's all thios sounds like.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "She needs help and needs to love herself for herself and her kids.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "jenna needs help, ot's sad she had to go down this route. I like Jenna but she needs the help and actually need to take accountabilty", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 3 },
  },
  {
    username: "pixiestar123",
    enabler_score: 9,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 4,
    jenna_message_count: 0,
    gaslighting_count: 4,
    pressure_count: 0,
    worst_messages: [
      { message: "Both of you are great, but together it's just toxic... Jenna needs help with her abandonment issues if she wants to have healthy relationships in the future. Please let this be the end of it.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I'm with you Aaron... however sleeping with someone that clearly has a history of abandonment issues, among other things, probably wasn't the best idea, especially when the relationship is done.", category: "PATHOLOGIZE", source: "asl_chat" },
      { message: "Her exaggerating the whole \"battery\" thing really is right out of scientology...", category: "MINIMIZE", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "PATHOLOGIZE", "MINIMIZE"],
    category_counts: { DARVO_ATTACK: 1, PATHOLOGIZE: 2, MINIMIZE: 1 },
  },
  {
    username: "signedwilliam",
    enabler_score: 9,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 5,
    jenna_message_count: 9,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "Unbiased. You both should handle this privately. Being former Sea Org members, I can only imagine how much PTSD is a factor in this beef.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "To be fair, I didn't know you both were dating. I thought it was a mutual friendship in protest of Scientology.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 2 },
    is_infiltrator: true,
  },
  {
    username: "soundtraveller54",
    enabler_score: 9,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 3,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "I hope you both get the psychological help you need - you are both traumatised by your past and you need to heal.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "You are both better than this situation, so you need to move on with your lives separately.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE", "WEAPONIZED_MOVE_ON"],
    category_counts: { FALSE_EQUIVALENCE: 1, WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "chuckbronson",
    enabler_score: 9,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 3,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "The Cops Won't Do Anything", category: "DISCOURAGE_LEGAL", source: "jenna_chat" },
    ],
    categories_triggered: ["DISCOURAGE_LEGAL"],
    category_counts: { DISCOURAGE_LEGAL: 1 },
    is_infiltrator: true,
  },
  {
    username: "dcourt_1",
    enabler_score: 9,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 14,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "Just walk away. Why are you publicly looking at this stream noting when he wronged you, and ignoring when you fucked up?", category: "DISCOURAGE_LEGAL", source: "jenna_chat" },
    ],
    categories_triggered: ["DISCOURAGE_LEGAL"],
    category_counts: { DISCOURAGE_LEGAL: 1 },
    is_infiltrator: true,
  },
  {
    username: "krisschumacher7707",
    enabler_score: 9,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 11,
    jenna_message_count: 15,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "I think there both at fault , but Jenna need to figure out how to handle her anger", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "Did you hear that Jenna, he is DONE move on", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE", "WEAPONIZED_MOVE_ON"],
    category_counts: { FALSE_EQUIVALENCE: 1, WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "motomechanic97",
    enabler_score: 9,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 101,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "THIS IS A WASTE OF TIME", category: "DISCOURAGE_LEGAL", source: "jenna_chat" },
    ],
    categories_triggered: ["DISCOURAGE_LEGAL"],
    category_counts: { DISCOURAGE_LEGAL: 1 },
    is_infiltrator: true,
  },
  {
    username: "mayersgirl",
    enabler_score: 9,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 2,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "Yes move on!!!", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "Why don't both of you get some help? If not for yourselves then for your kids.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON", "FALSE_EQUIVALENCE"],
    category_counts: { WEAPONIZED_MOVE_ON: 1, FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "soulie1971",
    enabler_score: 9,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 2,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "Jenna, this is so embarrassing! You both act like teenagers on hormonal rollercoaster without boundaries!!! This is pathetic and heartbreaking...", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "Why would you think your situation will have another outcome while repeating the same patterns again and again.. you both will destroy each other! Stop doing videos and get into serious therapy...", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 2 },
    is_infiltrator: true,
  },
  {
    username: "jenkess",
    enabler_score: 8,
    classification: "CENSOR",
    is_moderator: true,
    asl_message_count: 31,
    jenna_message_count: 0,
    gaslighting_count: 1,
    pressure_count: 0,
    worst_messages: [
      { message: "please remember you(all of us) are not responsible and should not be responsible for others mental health. If you have a loved one that you are fearful for, please reach out to get a well check", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 1 },
  },
  {
    username: "lenainlove",
    enabler_score: 8,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 2,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "plz! stop doing dirty laundry online.", category: "CREDIBILITY_ATTACK", source: "jenna_chat" },
    ],
    categories_triggered: ["CREDIBILITY_ATTACK"],
    category_counts: { CREDIBILITY_ATTACK: 1 },
    is_infiltrator: true,
  },
  {
    username: "laurac1082",
    enabler_score: 8,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 4,
    worst_messages: [
      { message: "You both need serious therapy!!!! Scientology is loving this and you both keep helping them!!", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "Both need to move on!! You are giving Scientology the weapon to destroy you both even more. STOP go back to the fight, don't let them win!!", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "Jenna please get help, you are not helping your cause. Move on and find peace. You are hurt and angry and this is not looking good for you.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE", "WEAPONIZED_MOVE_ON"],
    category_counts: { FALSE_EQUIVALENCE: 2, WEAPONIZED_MOVE_ON: 2 },
    is_infiltrator: false,
  },
  {
    username: "kikilhibou",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 4,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "Hi Love, I hope you are able to heal and move on. I've been in this situation and it is HARD.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON"],
    category_counts: { WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "stefsmith-c6k",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 4,
    jenna_message_count: 1,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "This is ridiculous! Go take care of your children! Both of you! Get therapy! This is all nonsense. And you know that deep down Jenna. Work on yourself and your children. PLEASE I am begging you", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "southernyankee-32",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 1,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "Grow up Jenna", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON"],
    category_counts: { WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "ajc1888",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 11,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "you both need a clean break after tonight", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "archesbro",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 1,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "@JennaMiscavige Are you in CA. and he is in FL. Do you both have joint custody and can't live together long term? I know the unknown dating world is scary but I dont think this works", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "snoodles1234",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 1,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "I unsubbed from Both channels. Time to move on. hopefully streets LA will keep this Drama off his channels.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON"],
    category_counts: { WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "lorraineinpnw",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 2,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "I pray for peace for both of you. Take care!", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "toph8298",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 18,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "Give him a day to get over it and he'll try hitting on Kelli Copter and Marilyn Honig lmao", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON"],
    category_counts: { WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "queenofmyhouse25",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 7,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "@genxray that's correct. Both are at fault for not keeping their hands to themselves. Jenna cannot excuse her downplay or excuse her throwing water etc.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "krissy0893",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 8,
    jenna_message_count: 1,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "what's the point of doing all this? you're both causing more damage. it's sad.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "tina-y7y",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 3,
    jenna_message_count: 4,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "I am off hope you both figure it out", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "acutepumpkinclodhopper",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 9,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "You both need JESUS", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "gardyloo3415",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 1,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "Girl.....just let it go", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON"],
    category_counts: { WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "sabrinaspeakeasy",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 6,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "I never such DARVO, he's clearly the abuser. He's done this to every woman that doesn't sweep for him. I get you both have trauma and codependency, but he's off the rails. Please stay away from him!", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "originaldragonmad",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 3,
    jenna_message_count: 2,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "Walk away and seek help. Both of you!", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "m.r.304",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 13,
    jenna_message_count: 8,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "please, most of us are loving both of you guys. Seek help and go on.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "diana-wl2vu",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 1,
    jenna_message_count: 4,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "tbh it's both of you fault but you each have to own that responsibility", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "treehuggingbuddhist",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 13,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "So now you know so move on please!", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON"],
    category_counts: { WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "harmdizzle1979",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 3,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "Why ARE you doing this though? I mean, I think both of you but It's just destructive. Your not going to feel better", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: true,
  },
  {
    username: "andreamalloy6266",
    enabler_score: 7,
    classification: "INFILTRATOR",
    is_moderator: false,
    asl_message_count: 13,
    jenna_message_count: 2,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "Please move on Jenna- go home and be happy", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON"],
    category_counts: { WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: true,
  },
  {
    username: "craigtaylor8592",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 4,
    jenna_message_count: 0,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "Trauma and BPD is really tough to live with but it can be treated.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "Check out dialectical behavior therapy, for emotional disregulation, life changing.", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 2 },
  },
  {
    username: "justified444",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 7,
    jenna_message_count: 0,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "Love them both, therapy is very important and WORTH THE COST.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "THERAPY X 2", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 2 },
  },
  {
    username: "great-gig-tcb",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 15,
    jenna_message_count: 2,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "Aaron look up BPD.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I relate to what Jenna is going through as it sounds a lot like my symptoms of Quiet BPD.", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 2 },
  },
  {
    username: "stacy-jw1ty",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 0,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "Therapy save lives! highly recommend it!", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "SCI has damaged her , damaged them both. Therapy IS a must for a healthy life.", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 2 },
  },
  {
    username: "hazelbea",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 1,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "This is sad. I hope you both get individual therapy because you're describing that you both need help with having healthy relationships and that takes individual work to learn how.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "This is sad and could end very badly. Everyone needs help that's involved and I hope everyone keeps themselves safe.", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 2 },
  },
  {
    username: "daylediamond",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 4,
    jenna_message_count: 0,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "therapy is available in San Diego!", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I've been in shoes like yours, but in CA. anti anxiety meds, therapy, it doesn't take two years to obtain this In California.", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 2 },
  },
  {
    username: "catsbatsandflowers",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 8,
    jenna_message_count: 0,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "The Cult of Scientology abuse still has its claws deep in Jenna's being...Therapy! Therapy! Therapy! Many positive thoughts for both of you", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "No magic pill is going to fix this type of anger. Meds and therapy will help but only if Jenna is open to change", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 2 },
  },
  {
    username: "kimberlyminer-t3l",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 0,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "I have felt the emptiness in my life, I forced myself into a relationship and friendships with the need to feel loved. It took me five years of therapy to realize and work through the trauma.", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "I would suggest saying if she is feeling that way, you are going to do what is best for her mental state and call 911. When we are deep in such a mind set we don't realize what we are really doing.", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 2 },
  },
  {
    username: "tinamcbride63",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 17,
    jenna_message_count: 0,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "Aaron you know deep down that this is Toxic af love Jenna but she needs help and its not you", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "God love her she needs help help with all this", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 2 },
  },
  {
    username: "1234cheerful",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 0,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "Isnt there a Section 5150 sort of thing in Florida? If she threatens self ham. Put up cameras all over and forget they are there; then keep a record of her crazy actions.", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "DARVO_REVERSE"],
    category_counts: { DARVO_ATTACK: 1, DARVO_REVERSE: 1 },
  },
  {
    username: "rickiemckenzie4984",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 6,
    jenna_message_count: 0,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "Break up with this psycho", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "Never go back with this crazy person", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK"],
    category_counts: { DARVO_ATTACK: 2 },
  },
  {
    username: "stephendolson-andrew3256",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 2,
    jenna_message_count: 0,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "Did she threaten Natalie and Cheryl as well?", category: "DARVO_REVERSE", source: "asl_chat" },
      { message: "Is it at all possible that you would get back together in the distant future if she gets therapy and meds and fixes this problem?", category: "DARVO_ATTACK", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_REVERSE", "DARVO_ATTACK"],
    category_counts: { DARVO_REVERSE: 1, DARVO_ATTACK: 1 },
  },
  {
    username: "kristinakurf",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 3,
    worst_messages: [
      { message: "he is not worth it, move on", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "Jenna get on the next flight, go non contact and move on with your life", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "Accept that you took him back but MOVE ON", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON"],
    category_counts: { WEAPONIZED_MOVE_ON: 3 },
    is_infiltrator: false,
  },
  {
    username: "mindybeee",
    enabler_score: 6,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "this is embarrassing", category: "CREDIBILITY_ATTACK", source: "jenna_chat" },
      { message: "we know this! this is just making you look bad", category: "CREDIBILITY_ATTACK", source: "jenna_chat" },
    ],
    categories_triggered: ["CREDIBILITY_ATTACK"],
    category_counts: { CREDIBILITY_ATTACK: 2 },
    is_infiltrator: false,
  },
  {
    username: "danc3488",
    enabler_score: 5,
    classification: "ENABLER",
    is_moderator: false,
    asl_message_count: 6,
    jenna_message_count: 0,
    gaslighting_count: 2,
    pressure_count: 0,
    worst_messages: [
      { message: "Taht is classic BPD. I'm sorry", category: "DARVO_ATTACK", source: "asl_chat" },
      { message: "She CAN control it. She CHOOSES not to. That's the saddest part", category: "PATHOLOGIZE", source: "asl_chat" },
    ],
    categories_triggered: ["DARVO_ATTACK", "PATHOLOGIZE"],
    category_counts: { DARVO_ATTACK: 1, PATHOLOGIZE: 1 },
  },
  {
    username: "theclassiccarnut",
    enabler_score: 4,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "sounds like an immature relationship. Like you are both teenagers. Grow up", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
      { message: "If you both get back together that would be stupid. Toxic immature relationship and both at fault", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON", "FALSE_EQUIVALENCE"],
    category_counts: { WEAPONIZED_MOVE_ON: 1, FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "stevieslick",
    enabler_score: 4,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "Former Scientology Staff member here. Both of you should realize that this is a toxic relationship and be glad that it is over.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "You both need to keep your eyes on the prize which is to save people from the cult of Scientology.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 2 },
    is_infiltrator: false,
  },
  {
    username: "1moonfairy525",
    enabler_score: 4,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "You both need help", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "You should all just move on...", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE", "WEAPONIZED_MOVE_ON"],
    category_counts: { FALSE_EQUIVALENCE: 1, WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: false,
  },
  {
    username: "veganostra7388",
    enabler_score: 4,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "This is not a both sides are wrong issue, he is a scary person please be safe", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "Supporting both sides is disgusting, do not support an abuser, stand with Jenna, stand with the victim", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 2 },
    is_infiltrator: false,
  },
  {
    username: "barbarastalavera",
    enabler_score: 4,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "it takes two to tango. nobody is innocent here.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "it takes two to tango", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 2 },
    is_infiltrator: false,
  },
  {
    username: "asap_lizzie",
    enabler_score: 4,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "Jenna, know I say this with respect as someone who has dealt with a Narcissistic Avoidant, this is a karmic relationship. You both need to go through the Dark Night of the Soul(heal) & let go", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "My advice, go hurt, go heal, allowing a new door to open. You can't move on until you heal. And you will.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE", "WEAPONIZED_MOVE_ON"],
    category_counts: { FALSE_EQUIVALENCE: 1, WEAPONIZED_MOVE_ON: 1 },
    is_infiltrator: false,
  },
  {
    username: "kristindewitt9059",
    enabler_score: 4,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "As a therapist this is stupid. STUPID. Grow up both of you.", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON", "FALSE_EQUIVALENCE"],
    category_counts: { WEAPONIZED_MOVE_ON: 1, FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "yeah-but-is-it-art",
    enabler_score: 4,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "BOTH of you have never learned relationship-skills. I feel sad about that. But for people who did, this is SO 'high school'... Please take some time to 'smell the grass' and centre yourself on you", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
      { message: "You BOTH confuse endless debates about your feelings = love. It is NOT. Love accepts and embraces, lifts you up. You need to BOTH do that tho. Also, do it in private? I feel like you guys are 15...", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 2 },
    is_infiltrator: false,
  },
  {
    username: "charlotteplant2262",
    enabler_score: 4,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 2,
    worst_messages: [
      { message: "Sounds like he doesn't want to be with you and you need to move on. Both of you need help", category: "WEAPONIZED_MOVE_ON", source: "jenna_chat" },
    ],
    categories_triggered: ["WEAPONIZED_MOVE_ON", "FALSE_EQUIVALENCE"],
    category_counts: { WEAPONIZED_MOVE_ON: 1, FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "brokensaide",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "aren't y'all like 40? this whole thing is high school af. i love you both, but this is cringe", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "susanr.562",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "@BrokenSaide Exactly. Both sides are wrong!", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "lisacny",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "You need to get some therapy or you may never have a healthy relationship. I think you are both toxic to each other.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "joseyesno5552",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "Jenna, this is just he say she say I think both of you are the fault and I put this on his life but going through all this and at least half of what he says has to be the truth. Get help.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "colleensreviewsandstories5213",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "this is why ITS A MISTAKE to have a public relationship online. you both have a decent following and because nobody is perfect and one or both of you is going to make a really big mistake and post it.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "maia.in" + ".nightmareland",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "I just watched the start of his live, but he made me uncomfortable and a mod told me to leave when I pointed that out and said that I wanted both sides, so I did and unsubbed.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "everydayissaturdayexceptsunday",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "If he's so terrible, why did you keep going back to him. You both need serious help but you have a mental illness.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "gigilynn3482",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "Jenna, you know you don't need him. You will be alright. He will too, but you both doing this publicly is bad for both of you.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "mstasha217",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "@luva same. But you guys this is so place the most craziest thing I've ever seen two adults Do in my entire life... You both need to take down all of these posts all of them all of them all of them grow", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "snaketology",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "Marilyn got comfortable up there. Saying too much for supporting both sides", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "hippychicken82",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "u need a really good therapist and I really wish u the best, you both need extensive therapy and I wish u can heal. sending hugs", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "joemac3738",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "this is all pathetic. why are you both publishing this online", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "firetruck88",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "Oh, I have both of you recorded, none of this is going away.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "larky3487",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "your both toxic. girl you live in cali he is in florida still married...how long was this suppose to last...girl let him go, you deserve better.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "auntiejans_rocksnraccoons",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "I think you BOTH could benefit from therapy!!", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
  {
    username: "calincoop",
    enabler_score: 2,
    classification: "FALSE_NEUTRAL",
    is_moderator: false,
    asl_message_count: 0,
    jenna_message_count: 0,
    gaslighting_count: 0,
    pressure_count: 1,
    worst_messages: [
      { message: "He's making your story sound like his and Lindsey's story . He treated you both the same.", category: "FALSE_EQUIVALENCE", source: "jenna_chat" },
    ],
    categories_triggered: ["FALSE_EQUIVALENCE"],
    category_counts: { FALSE_EQUIVALENCE: 1 },
    is_infiltrator: false,
  },
];
